FROM mcr.microsoft.com/dotnet/runtime-deps:8.0.1-alpine3.19-amd64 as runtime
RUN adduser -S appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0.101-alpine3.19-amd64 AS publish
WORKDIR /src
COPY src/. .
RUN ls -lah
RUN pwd

WORKDIR /src/web/Web
RUN ls -lah
RUN pwd
RUN dotnet restore -r linux-musl-x64
RUN dotnet publish \
    -c Release \
    --no-restore \
    -o /publish \
    -r linux-musl-x64 \
    --self-contained true \
    -p:PublishSingleFile=true

FROM runtime
WORKDIR /app
COPY --chown=appuser:root --chmod=755 --from=publish /publish .

RUN mkdir /data \
    && chown -R appuser:root /data \
    && chmod -R 755 /data

USER appuser
ENV HTTP_PORTS=80
CMD ["./Web"]
