FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-bookworm-slim-amd64 as runtime
WORKDIR /app
RUN groupadd -g 1001 user
RUN useradd -m user -g 1001 -u 1001

FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim-amd64 AS publish
WORKDIR /src

COPY . .
RUN dotnet restore "web/src/web/web.csproj" -r linux-x64

RUN dotnet publish "web/src/web/web.csproj" \
    -c Release \
    --no-restore \
    -o /publish \
    -r linux-x64 \
    --self-contained true \
    -p:PublishSingleFile=true

FROM runtime
COPY --from=publish /publish .

RUN chown -R 1001:1001 /app
RUN chmod -R 755 /app

RUN mkdir /data
RUN chown -R 1001:1001 /data
RUN chmod -R 755 /data

USER user
ENV HTTP_PORTS=80
CMD ["./web"]
