FROM mcr.microsoft.com/dotnet/runtime-deps:8.0.1-bookworm-slim-amd64 as runtime
RUN apt-get update \
	&& apt-get install -y --no-install-recommends --no-install-suggests \
		python3=3.11.2-1+b1 \
		lib32z1=1:1.2.13.dfsg-1 \
	&& rm -rf /var/lib/apt/lists/*

RUN useradd -m appuser -u 1001

FROM mcr.microsoft.com/dotnet/sdk:8.0.101-bookworm-slim-amd64 AS publish
WORKDIR /src
COPY src/. .

WORKDIR /src/instance/Instance
RUN dotnet restore -r linux-x64
RUN dotnet publish \
    -c Release \
    --no-restore \
    -o /publish \
    -r linux-x64 \
    --self-contained true \
    -p:PublishSingleFile=true

FROM runtime
WORKDIR /app
COPY --chown=appuser:root --chmod=770 --from=publish /publish .
RUN mkdir /data \
    && chown -R appuser:root /data \
    && chmod -R 770 /data
    
USER appuser
ENV HTTP_PORTS=11111
CMD ["./Instance"]