name: build docker images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Version: "3.${{ github.run_attempt }}"

    steps:
    - uses: actions/checkout@v3
    - name: Output version
      run: echo "${{ env.Version }}"
    - name: Build cs-controller-instance Docker image
      run: docker build . --file Dockerfile_instance --tag cs-controller-instance:${{ env.Version }}
    - name: Build cs-controller-web Docker image
      run: docker build . --file Dockerfile_web --tag cs-controller-web:${{ env.Version }}
